### PR TITLE
Fix crash on spread operator on fetch

### PR DESCRIPTION
**Pull request by dylanarmstrong**
There is a bug with line 274 in util/get-fic.js
`...fetch(fic.cover, {referer: fic.link}).spread...`
Promises don't have spread method, I just adjusted it so it would use `Bluebird.resolve` around it.

Can be tested with:
`./ff.js get https://www.fanfiction.net/s/8400788/1/Inquisitor-Carrow-and-the-GodEmperorless-Heathens`
`./ff.js gen -o epub inquisitor-carrow-and-the-godemperorless-heathens.fic.toml`

It will give the following:
```
ERROR Error in get fic TypeError: fetch(...).spread is not a function
    at Bluebird.each.then.then.then.then (/Users/asdf/Documents/src/fetch-fic/util/get-fic.js:274:54)
    at tryCatcher (/Users/asdf/Documents/src/fetch-fic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/asdf/Documents/src/fetch-fic/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/asdf/Documents/src/fetch-fic/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/asdf/Documents/src/fetch-fic/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/asdf/Documents/src/fetch-fic/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/asdf/Documents/src/fetch-fic/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/asdf/Documents/src/fetch-fic/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/asdf/Documents/src/fetch-fic/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
Exited without resolving promises!
```

### CODE REVIEW

**Comment by iarna** [comment]
Hey, it looks like there are three distinct things here. A SB rate limiting change (mine is now actually even stricter, a concurrency of 1 and rps of 0.5), a new xenforo site and a patch for a crash.

The rate limit change and crash patch have been obsoleted (sorry I didn't notice this till now‼).

The new xenforo site, I'll cherry-pick in though, thanks for that! =)

**Comment by iarna** [comment]
(I'll comment with the commitid when it's added)

**Comment by dylanarmstrong** [comment]
Hey @iarna, sorry I pushed to the branch and got unrelated things mixed into this pull request!

The Alternate History patch doesn't work just FYI. I haven't had time to really look into it more.

**Comment by iarna** [comment]
@meinhimmel Yeah, I fixed it up! It's landed as fa5f913 and seems to work fine. Looking around on AlternateHistory I  couldn't find any posts with threadmarks or index posts, so it'll typically just bring in the first post of the thread. I don't have a mode at the moment for "turn the entire thread into an epub". I _do_ have something to grab all posts from the OP (`ff get --all-posts`) that may be useful there though. Also it should maybe be renamed to be less confusing. 😅

**Comment by iarna** [comment]
Ah I spoke too soon! I found a post with some threadmarks and that's definitely behaving a wee bit weird… mm…

**Comment by iarna** [comment]
Ah, and fixed in a0dc019. The threadmark URL wasn't being computed correctly for alternate history due to its having a prefix in front of its urls.

**Pull request closed without merging**
